package com.fh.service.personmanager.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.fh.service.personmanager.UserBasicManager;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-03-26T16:00:46.609+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "UserBasicServiceService", 
                  wsdlLocation = "http://59.222.237.135:9016/UnitWebservice/ws/userbasic?wsdl",
                  targetNamespace = "http://impl.personmanager.service.fh.com/") 
public class UserBasicServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.personmanager.service.fh.com/", "UserBasicServiceService");
    public final static QName UserBasicServicePort = new QName("http://impl.personmanager.service.fh.com/", "UserBasicServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://59.222.237.135:9016/UnitWebservice/ws/userbasic?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserBasicServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://59.222.237.135:9016/UnitWebservice/ws/userbasic?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserBasicServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserBasicServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserBasicServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserBasicServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserBasicServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserBasicServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UserBasicManager
     */
    @WebEndpoint(name = "UserBasicServicePort")
    public UserBasicManager getUserBasicServicePort() {
        return super.getPort(UserBasicServicePort, UserBasicManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserBasicManager
     */
    @WebEndpoint(name = "UserBasicServicePort")
    public UserBasicManager getUserBasicServicePort(WebServiceFeature... features) {
        return super.getPort(UserBasicServicePort, UserBasicManager.class, features);
    }

}
