
package com.fh.service.personmanager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-03-26T16:00:46.550+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "ServiceException", targetNamespace = "http://personmanager.service.fh.com/")
public class ServiceException_Exception extends Exception {
    
    private com.fh.service.personmanager.ServiceException serviceException;

    public ServiceException_Exception() {
        super();
    }
    
    public ServiceException_Exception(String message) {
        super(message);
    }
    
    public ServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException_Exception(String message, com.fh.service.personmanager.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException_Exception(String message, com.fh.service.personmanager.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public com.fh.service.personmanager.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
