package com.fh.service.personmanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-03-26T16:00:46.587+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://personmanager.service.fh.com/", name = "UserBasicManager")
@XmlSeeAlso({ObjectFactory.class})
public interface UserBasicManager {

    @WebMethod
    @RequestWrapper(localName = "listByUnitCode", targetNamespace = "http://personmanager.service.fh.com/", className = "com.fh.service.personmanager.ListByUnitCode")
    @ResponseWrapper(localName = "listByUnitCodeResponse", targetNamespace = "http://personmanager.service.fh.com/", className = "com.fh.service.personmanager.ListByUnitCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.fh.service.personmanager.UserVo> listByUnitCode(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws ServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "detailById", targetNamespace = "http://personmanager.service.fh.com/", className = "com.fh.service.personmanager.DetailById")
    @ResponseWrapper(localName = "detailByIdResponse", targetNamespace = "http://personmanager.service.fh.com/", className = "com.fh.service.personmanager.DetailByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.fh.service.personmanager.UserVo detailById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    ) throws ServiceException_Exception;
}
